#pragma once
#include <iostream>
#include <string>
#include <fstream>
#include <iomanip>
#include <cwchar>
#include <ctime>
#include <cwchar>
#include <tchar.h>
#include <stack>
#include <deque>
#include <list>
#include <algorithm>
#include <Windows.h>

#include "Log.h"
#include "Exception.h"
#include "Lexical_Analysis.h"
#include "Sematic_Analysis.h"
#include "Parm.h"
#include "MFST.h"
#include "Greibach.h"
#include "FST.h"
#include "Input.h"
#include "IDTABLE.h"
#include "LEXTABLE.h"
#include "Polish_Notation.h"
#include "Code_Generator.h"
